### ISSUE TITLE
Epic Story

### ISSUE THREAD

**Issue by richhosek** [Project1Team0RV/Project1#2]
As Instructors
We want to manage student projects
So that we can keep track of everything easily

- [x] Create Project Teams
- [x] Create Team Slack Channels
- [x] Create GitHub Organization
- [x] Create Repos
- [x] Create Branch Rule
- [x] New Branch
- [ ] Demo Pull Request
- [ ] Demo Merge Conflict
